apiVersion: apps/v1
kind: Deployment
metadata:
  name:  image-check
  namespace: default
  labels:
    app: image-check
spec:
  selector:
    matchLabels:
      app: image-check
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: image-check
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
#      initContainers:
#        - name:
      containers:
        - name:  admissionpod
          image:  harbor.myshuju.top/public/admissionpod:v0.0.11
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: MODIFY_IMG_DEFAULT
              value: "true"
          ports:
            - containerPort:  1443
              name:  pod-dmission
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: tls
              mountPath: /etc/webhook/certs
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: tls
          secret:
            secretName: admissionpod-tls
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: image-check
  namespace: default
spec:
  selector:
    app: image-check
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: image-check
      protocol: TCP
      port: 443
      targetPort: 1443