---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: image-check
      namespace: default
      path: /mutate
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtakNDQW9LZ0F3SUJBZ0lVRjVzVWt1eC9tNW1NK3RIdk8ydHB6alVuVFJnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEl6TURNd05ERTVOREl3TUZvWERUSTRNRE13TWpFNU5ESXdNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdHpRNWVONzdQc2FTZkJZYVBlOTQKK25KU3hhU3BWVlhmRms3MzcvcmRzNGx0Q0txZ3VXWDNjbEMyU2U1OHRSVVpENG9lRnUxR0VEaHV1MHZDMkh4QworeFV2d2xYc0VPN3dGdjVJdVlYUkZBeDV4bVZ4MW9OUnRNV25BRXVDakFCY21DT3FuVFZ6NTd1eWs5VndJazZNClJHeElaMFAzREt2dUxSa09LUXZBbEl5dUI3Rm9yZGZFMExiRFBHQ2lVekl3RlMxc3BlTWRCeDN5Z1NMSUQvNG0KaUlqRWNabkM5VU1YYksxQmc0Nzd0Mzl5VDFSMU50U283RzVqemFrdjAxS1duSFV4ejBwaUJySVZFUWJLUlNaSgpwa202WkpRNVJGUHZPbjZvMlBrR2Fiemw4YVBEdVRFWm9mZFB0K2VxdzhPN1cvOUM5cldIMDVCUGg4ekdjR3d1ClB3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlYKSFE0RUZnUVVPTkxESEJwMHFEMzZYUXNkNEV6eU9nZXRWVnN3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUp0ZgpYaVlUYmh3bk5OMU9PV2grUUxIbmQ0ZGhQQm02Nnp3ajBPaVlHd284VDM5UDB0VTJCak91eXFqOTZpNmN4eEQwCmhvcDdOem5BLzBPSDlId01HZFBlZUcvbnA3U2pOMlROcXc4dTh0U2YrOFdwdlRJM3BVT3FhVVJaYXNoZTQzSHoKZ2lhdUNZVGxZcEtpY2FPS2VoNmRjYXlnUDBRbXM5cmZGdURaNmhGaEY5eEtEZFkwN2ptU0J6Q3JUUXB0eFl0dQoxZ2NZMjlFdHFpUG1NT3ZPbGdjbEJKLzFtUnNpL3gzMVNOS3lOYW5WYXBHTDlZNnJVYndHdTlsWnV4ckpyOFJMClZiclFRcm9lTGtFT3MyeHRBc3JuM2syWEZhZm83YkNvSkl6d0I1V2h4VTE3S0Rxa1dDNzVLaU1JbGFqamJDczIKeXlTbk91c1g1QUp2QzBJcVBRND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  failurePolicy: Fail
  name: pod.mutate.myshuju.top
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: image-check
      namespace: default
      path: /validate
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtakNDQW9LZ0F3SUJBZ0lVRjVzVWt1eC9tNW1NK3RIdk8ydHB6alVuVFJnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEl6TURNd05ERTVOREl3TUZvWERUSTRNRE13TWpFNU5ESXdNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdHpRNWVONzdQc2FTZkJZYVBlOTQKK25KU3hhU3BWVlhmRms3MzcvcmRzNGx0Q0txZ3VXWDNjbEMyU2U1OHRSVVpENG9lRnUxR0VEaHV1MHZDMkh4QworeFV2d2xYc0VPN3dGdjVJdVlYUkZBeDV4bVZ4MW9OUnRNV25BRXVDakFCY21DT3FuVFZ6NTd1eWs5VndJazZNClJHeElaMFAzREt2dUxSa09LUXZBbEl5dUI3Rm9yZGZFMExiRFBHQ2lVekl3RlMxc3BlTWRCeDN5Z1NMSUQvNG0KaUlqRWNabkM5VU1YYksxQmc0Nzd0Mzl5VDFSMU50U283RzVqemFrdjAxS1duSFV4ejBwaUJySVZFUWJLUlNaSgpwa202WkpRNVJGUHZPbjZvMlBrR2Fiemw4YVBEdVRFWm9mZFB0K2VxdzhPN1cvOUM5cldIMDVCUGg4ekdjR3d1ClB3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlYKSFE0RUZnUVVPTkxESEJwMHFEMzZYUXNkNEV6eU9nZXRWVnN3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUp0ZgpYaVlUYmh3bk5OMU9PV2grUUxIbmQ0ZGhQQm02Nnp3ajBPaVlHd284VDM5UDB0VTJCak91eXFqOTZpNmN4eEQwCmhvcDdOem5BLzBPSDlId01HZFBlZUcvbnA3U2pOMlROcXc4dTh0U2YrOFdwdlRJM3BVT3FhVVJaYXNoZTQzSHoKZ2lhdUNZVGxZcEtpY2FPS2VoNmRjYXlnUDBRbXM5cmZGdURaNmhGaEY5eEtEZFkwN2ptU0J6Q3JUUXB0eFl0dQoxZ2NZMjlFdHFpUG1NT3ZPbGdjbEJKLzFtUnNpL3gzMVNOS3lOYW5WYXBHTDlZNnJVYndHdTlsWnV4ckpyOFJMClZiclFRcm9lTGtFT3MyeHRBc3JuM2syWEZhZm83YkNvSkl6d0I1V2h4VTE3S0Rxa1dDNzVLaU1JbGFqamJDczIKeXlTbk91c1g1QUp2QzBJcVBRND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  failurePolicy: Fail
  name: pod.valid.myshuju.top
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None
